name: BigQuery Data Loader

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  load_bigquery_data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install google-cloud-bigquery

    - name: Authenticate with Google Cloud
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ runner.temp }}/gcp_key.json
      run: |
        echo "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}" > $GOOGLE_APPLICATION_CREDENTIALS

    - name: Run BigQuery Loader
      run: python bigquery_loader.py
